// Generated by CoffeeScript 1.9.2
(function() {
  var fs, load_json, readFilePromised;

  fs = require('fs');

  readFilePromised = function(file) {
    return new Promise(function(resolve, reject) {
      return fs.readFile(file, function(err, ret) {
        if (err !== null) {
          return reject(err);
        } else {
          return resolve(ret);
        }
      });
    });
  };

  load_json = function(json_file) {
    var ret;
    ret = void 0;
    return readFilePromised(json_file).then(function(file_content) {
      return ret = file_content;
    }).then(JSON.parse)["catch"](function(err) {
      console.log("error catched");
      console.log("ret is " + ret);
      if (err.code === 'ENOENT') {
        console.log("ENOENT catched");
        return null;
      } else if (err instanceof SyntaxError) {
        console.log("SyntaxError catched");
        console.log("Before removing comments: " + ret);
        ret = ret.replace('/\/\//', '');
        console.log("After removing comments: " + ret);
        ret = JSON.parse(ret);
        return console.log("After parsing: " + val);
      } else {
        console.log("Other error catched.");
        throw err;
      }
    });
  };

  load_json('commented.json').then(function(val) {
    return console.log("commented: " + val);
  });

}).call(this);
